"""add role to users

Revision ID: 3836a3ef8258
Revises: 6fe4cbf638b7
Create Date: 2026-04-27 11:57:36.866981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3836a3ef8258'
down_revision: Union[str, Sequence[str], None] = '6fe4cbf638b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_memory', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_memory', 'companies', ['company_id'], ['id'])
    op.add_column('audit_jobs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'audit_jobs', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'audit_jobs', type_='foreignkey')
    op.drop_column('audit_jobs', 'company_id')
    op.drop_constraint(None, 'agent_memory', type_='foreignkey')
    op.drop_column('agent_memory', 'company_id')
    # ### end Alembic commands ###
